// src/screens/seller/Products/SellerProductsScreen.styles.ts
import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F5' },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: '#FFFFFF',
    paddingTop: Platform.OS === 'ios' ? 52 : 20,
    paddingBottom: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  iconBtnText: { fontSize: 18 },
  notifDot: {
    position: 'absolute',
    top: 10,
    right: 11,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
    borderWidth: 2,
    borderColor: '#F3F4F6',
  },

  // ── Search row ────────────────────────────────────────────────────────────
  searchRow: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingBottom: 12,
    paddingTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 40,
    gap: 8,
    borderWidth: 0.5,
    borderColor: '#E5E7EB',
  },
  searchIcon: { fontSize: 14 },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#111827',
    paddingVertical: 0,
  },
  iconSquare: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: '#E5E7EB',
  },
  iconSquareActive: {
    backgroundColor: '#111827',
    borderColor: '#111827',
    borderWidth: 1,
  },
  iconSquareText: { fontSize: 18, color: '#6B7280' },

  // ── Filter chips ──────────────────────────────────────────────────────────
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 7,
    gap: 5,
  },
  filterChipActive: {
    backgroundColor: '#111827',
  },
  filterChipText: {
    fontSize: 13,
    color: '#9CA3AF',
    fontWeight: '500',
  },
  filterChipCaret: {
    fontSize: 11,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  clearChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEE2E2',
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  clearChipText: {
    fontSize: 12,
    color: '#991B1B',
    fontWeight: '600',
  },

  // ── Dropdown ──────────────────────────────────────────────────────────────
  dropdownWrapper: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 188 : 156,
    left: 0,
    right: 0,
    zIndex: 999,
    paddingHorizontal: 12,
  },
  dropdownWrapperCategory: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 188 : 156,
    left: 0,
    right: 0,
    zIndex: 999,
    paddingHorizontal: 12,
    alignItems: 'flex-start',
    paddingLeft: 118,
  },
  dropdown: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#E5E7EB',
    minWidth: 140,
    alignSelf: 'flex-start',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F3F4F6',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownItemActive: { backgroundColor: '#F9FAFB' },
  dropdownItemText: { fontSize: 13, color: '#374151', fontWeight: '500' },
  dropdownItemTextActive: { color: '#111827', fontWeight: '700' },

  // ── LIST product card ─────────────────────────────────────────────────────
  list: { padding: 12, paddingBottom: 30, gap: 10 },

  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: '#E5E7EB',
  },
  productCardPressed: { opacity: 0.8 },

  imageWrap: {
    width: 80,
    height: 80,
    backgroundColor: '#F3F4F6',
    flexShrink: 0,
    borderRightWidth: 0.5,
    borderRightColor: '#E5E7EB',
  },
  imageActual: { width: 80, height: 80 },
  imagePlaceholder: {
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
  },
  imagePlaceholderText: { fontSize: 24 },

  info: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },

  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
    marginBottom: 3,
  },
  statusBadgeActive:       { backgroundColor: '#ECFDF5' },
  statusBadgeArchived:     { backgroundColor: '#F3F4F6' },
  statusDot:               { width: 6, height: 6, borderRadius: 3 },
  statusDotActive:         { backgroundColor: '#22C55E' },
  statusDotArchived:       { backgroundColor: '#9CA3AF' },
  statusBadgeText:         { fontSize: 11, fontWeight: '500' },
  statusBadgeTextActive:   { color: '#065F46' },
  statusBadgeTextArchived: { color: '#6B7280' },

  productName: {
    fontSize: 13,
    fontWeight: '500',
    color: '#111827',
    lineHeight: 18,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 5,
    marginTop: 2,
  },
  productPrice: { fontSize: 13, fontWeight: '600', color: '#111827' },
  dotSeparator: { fontSize: 12, color: '#D1D5DB', fontWeight: '600' },
  colorDot: {
    width: 11, height: 11, borderRadius: 6,
    borderWidth: 0.5, borderColor: '#E5E7EB',
  },
  colorLabel: { fontSize: 12, color: '#9CA3AF' },
  stockText:  { fontSize: 12, color: '#9CA3AF' },

  actions: {
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 6,
    paddingRight: 12,
    paddingLeft: 4,
  },
  actionBtn: {
    width: 34, height: 34, borderRadius: 8,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#F3F4F6',
    borderWidth: 0.5, borderColor: '#E5E7EB',
  },
  actionBtnText: { fontSize: 14, color: '#374151' },

  // ── GRID product card ─────────────────────────────────────────────────────
  gridList: {
    padding: 12,
    paddingBottom: 30,
  },
  gridColumnWrapper: {
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  gridCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    width: '48.5%',
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: '#E5E7EB',
  },
  gridCardPressed: { opacity: 0.8 },
  gridImageWrap: {
    width: '100%',
    height: 120,
    backgroundColor: '#F3F4F6',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  gridImageActual: { width: '100%', height: 120 },
  gridImagePlaceholder: {
    width: '100%',
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
  },
  gridImagePlaceholderText: { fontSize: 30 },
  gridInfo: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 4,
    gap: 3,
  },
  gridProductName: {
    fontSize: 12,
    fontWeight: '500',
    color: '#111827',
    lineHeight: 16,
  },
  gridProductPrice: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
    marginTop: 2,
  },
  gridStockText: { fontSize: 11, color: '#9CA3AF' },
  gridActions: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 10,
    borderTopWidth: 0.5,
    borderTopColor: '#F3F4F6',
  },
  gridActionBtn: {
    flex: 1,
    height: 30,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
    borderWidth: 0.5,
    borderColor: '#E5E7EB',
  },
  gridActionBtnText: { fontSize: 13, color: '#374151' },

  // ── Toast ─────────────────────────────────────────────────────────────────
  toast: {
    position: 'absolute',
    bottom: 20, left: 16, right: 16,
    backgroundColor: '#111827',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16, paddingVertical: 13,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.2, shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },
  toastCheckWrap: {
    width: 24, height: 24, borderRadius: 12,
    backgroundColor: '#22C55E',
    alignItems: 'center', justifyContent: 'center',
  },
  toastCheck: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  toastText:  { flex: 1, color: '#FFFFFF', fontSize: 13, fontWeight: '500' },
  toastClose: { color: '#6B7280', fontSize: 14 },

  // ── Empty ─────────────────────────────────────────────────────────────────
  emptyWrap:  {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 48,
    paddingHorizontal: 32,
  },
  emptyIcon:  { fontSize: 24 },
  emptyTitle: { fontSize: 15, fontWeight: '500', color: '#111827', marginTop: 14 },
  emptyText:  { fontSize: 13, color: '#9CA3AF', marginTop: 6, textAlign: 'center', lineHeight: 20 },
});