// src/screens/seller/Orders/SellerOrderDetailScreen.styles.ts
import { StyleSheet, Platform } from 'react-native';

export const detailStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F4F4F4' },

  // ── Top hero header (dark) ────────────────────────────────────────────────
  hero: {
    backgroundColor: '#1A1A2E',
    paddingTop: Platform.OS === 'ios' ? 56 : 28,
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  heroBack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 18,
  },
  heroBackText: { fontSize: 14, color: '#AAAACC', fontWeight: '600' },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  heroOrderId: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  heroDate: { fontSize: 12, color: '#8888AA', marginTop: 3 },
  heroAmount: {
    fontSize: 26,
    fontWeight: '800',
    color: '#F97316',
    letterSpacing: -0.5,
  },
  heroAmountLabel: { fontSize: 11, color: '#8888AA', textAlign: 'right', marginTop: 2 },

  // ── Status badge (in hero) ────────────────────────────────────────────────
  heroBadgeWrap: { marginTop: 16 },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 7,
  },
  heroBadgeDot: { width: 8, height: 8, borderRadius: 4 },
  heroBadgeText: { fontSize: 13, fontWeight: '700' },

  // ── Timeline ──────────────────────────────────────────────────────────────
  timelineCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 14,
    marginTop: 14,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  timelineTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#AAAAAA',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 14,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 0,
  },
  timelineLeft: { alignItems: 'center', width: 28 },
  timelineNodeDone: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#F97316',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineNodeActive: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFF5EE',
    borderWidth: 2,
    borderColor: '#F97316',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineNodePending: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#F2F2F2',
    borderWidth: 2,
    borderColor: '#DDDDDD',
  },
  timelineNodeCancelled: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFE5E5',
    borderWidth: 2,
    borderColor: '#F43F5E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineNodeText: { fontSize: 11, color: '#FFFFFF', fontWeight: '800' },
  timelineNodeActiveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F97316',
  },
  timelineConnector: {
    width: 2,
    flex: 1,
    minHeight: 20,
    backgroundColor: '#EEEEEE',
    marginVertical: 2,
    alignSelf: 'center',
  },
  timelineConnectorDone: { backgroundColor: '#F97316' },
  timelineContent: { flex: 1, paddingLeft: 12, paddingBottom: 16 },
  timelineLabel: { fontSize: 14, fontWeight: '700', color: '#BBBBBB' },
  timelineLabelDone: { color: '#111111' },
  timelineLabelActive: { color: '#F97316' },
  timelineSub: { fontSize: 12, color: '#BBBBBB', marginTop: 2 },
  timelineSubDone: { color: '#888888' },

  // ── Section card (shared) ─────────────────────────────────────────────────
  sectionCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 14,
    marginTop: 12,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#AAAAAA',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sectionCount: {
    fontSize: 12,
    fontWeight: '700',
    color: '#F97316',
    backgroundColor: '#FFF5EE',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: 'hidden',
  },

  // ── Order item row ────────────────────────────────────────────────────────
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F9F9F9',
  },
  itemImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
    overflow: 'hidden',
  },
  itemImageActual: { width: 60, height: 60 },
  itemImagePlaceholder: {
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
  },
  itemImagePlaceholderText: { fontSize: 24 },
  itemInfo: { flex: 1 },
  itemName: { fontSize: 14, fontWeight: '700', color: '#111111', lineHeight: 19 },
  itemMeta: { fontSize: 12, color: '#888888', marginTop: 3 },
  itemPrice: { fontSize: 15, fontWeight: '800', color: '#111111' },

  // ── Info rows (shipping, payment) ─────────────────────────────────────────
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F9F9F9',
    gap: 10,
  },
  infoIcon: { fontSize: 16, width: 24, textAlign: 'center', marginTop: 1 },
  infoBlock: { flex: 1 },
  infoLabel: { fontSize: 11, color: '#AAAAAA', fontWeight: '600', marginBottom: 2 },
  infoValue: { fontSize: 13, color: '#222222', fontWeight: '500', lineHeight: 18 },

  // ── Summary / totals ──────────────────────────────────────────────────────
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F9F9F9',
  },
  summaryLabel: { fontSize: 13, color: '#888888' },
  summaryValue: { fontSize: 13, color: '#333333', fontWeight: '600' },
  summaryTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  summaryTotalLabel: { fontSize: 15, fontWeight: '700', color: '#111111' },
  summaryTotalValue: { fontSize: 18, fontWeight: '800', color: '#F97316' },

  // ── Action footer ─────────────────────────────────────────────────────────
  footer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 32 : 16,
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE',
    flexDirection: 'row',
    gap: 10,
  },
  footerBtnSecondary: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFE5E5',
    borderWidth: 1,
    borderColor: 'rgba(220,38,38,0.2)',
  },
  footerBtnSecondaryText: { fontSize: 14, fontWeight: '700', color: '#CC0000' },
  footerBtnPrimary: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F97316',
  },
  footerBtnPrimaryText: { fontSize: 14, fontWeight: '700', color: '#FFFFFF' },
  footerBtnDisabled: { backgroundColor: '#F2F2F2' },
  footerBtnDisabledText: { color: '#AAAAAA' },
  footerBtnPressed: { opacity: 0.82 },

  bottomSpacer: { height: 20 },
});