// src/screens/seller/AddProduct/AddProductScreen.styles.ts
import { StyleSheet, Platform } from 'react-native';

const BLACK   = '#111827';
const WHITE   = '#FFFFFF';
const BG      = '#F5F5F5';
const BORDER  = '#E5E7EB';
const TEXT    = '#111827';
const TEXT2   = '#6B7280';
const TEXT3   = '#9CA3AF';
const SURFACE = '#F3F4F6';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },

  // ── Header ──────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 52 : 44,
    paddingBottom: 12,
    backgroundColor: WHITE,
    borderBottomWidth: 0.5,
    borderBottomColor: BORDER,
  },
  backText: { fontSize: 16, color: BLACK, fontWeight: '600' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: TEXT },
  headerSpacer: { width: 48 },

  // ── Body ────────────────────────────────────────────────────
  body: { padding: 12, paddingBottom: 60 },

  // ── Card ────────────────────────────────────────────────────
  card: {
    backgroundColor: WHITE,
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: BORDER,
    overflow: 'hidden',
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: TEXT3,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  cardSubLabel: {
    fontSize: 11,
    color: TEXT3,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F3F4F6',
  },
  cardHeaderSingle: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F3F4F6',
  },
  cardBody: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },

  // ── Fields ──────────────────────────────────────────────────
  label: { fontSize: 13, fontWeight: '500', color: TEXT2, marginBottom: 6 },
  req: { color: BLACK },
  fieldGap: { height: 12 },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 8,
    backgroundColor: WHITE,
    paddingHorizontal: 12,
    height: 46,
    gap: 8,
  },
  inputWrapError: { borderColor: '#EF4444' },
  inputWrapMulti: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 8,
    backgroundColor: WHITE,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
  },
  inputIcon: { fontSize: 14, color: TEXT3 },
  input: { flex: 1, fontSize: 14, color: TEXT, fontWeight: '400' },
  inputMulti: {
    fontSize: 14,
    color: TEXT,
    fontWeight: '400',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  errorText: { fontSize: 11, color: '#EF4444', marginTop: 4 },

  // ── Media ───────────────────────────────────────────────────
  mediaScroll: { marginHorizontal: -2 },
  mediaRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 2, paddingBottom: 4 },
  mediaThumbMain: {
    width: 110,
    height: 130,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  mediaThumb: {
    width: 88,
    height: 104,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  mediaImg: { width: '100%', height: '100%', resizeMode: 'cover' },
  coverBadge: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    backgroundColor: 'rgba(0,0,0,0.65)',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  coverBadgeText: {
    fontSize: 9,
    color: WHITE,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  removeBtn: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeBtnText: { color: WHITE, fontSize: 9, fontWeight: '800' },
  addPhotoBtn: {
    width: 88,
    height: 104,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: SURFACE,
    gap: 5,
  },
  addPhotoIcon: { fontSize: 20, color: TEXT3 },
  addPhotoText: { fontSize: 10, color: TEXT3, fontWeight: '500' },
  mediaHint: {
    fontSize: 11,
    color: TEXT3,
    textAlign: 'center',
    marginTop: 8,
  },

  // ── Chips (generic) ─────────────────────────────────────────
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: SURFACE,
  },
  chipActive: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BLACK,
    backgroundColor: BLACK,
  },
  chipText: { fontSize: 12, fontWeight: '500', color: TEXT2 },
  chipTextActive: { fontSize: 12, fontWeight: '500', color: WHITE },

  // ── Size Group Container ─────────────────────────────────────
  sizeGroupContainer: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: WHITE,
  },
  sizeGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: SURFACE,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  sizeGroupIcon: { fontSize: 14 },
  sizeGroupTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: TEXT2,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    flex: 1,
  },
  sizeGroupBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: BLACK,
  },
  sizeGroupBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: WHITE,
  },
  sizeChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 12,
  },

  // ── Sizes ───────────────────────────────────────────────────
  clearAllText: {
    fontSize: 12,
    color: TEXT3,
    fontWeight: '500',
  },
  sizeChip: {
    minWidth: 52,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: SURFACE,
    paddingHorizontal: 10,
  },
  sizeChipActive: {
    minWidth: 52,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: BLACK,
    backgroundColor: BLACK,
    paddingHorizontal: 10,
  },
  // Extra width for shoe size ranges like "35–37"
  sizeChipWide: {
    minWidth: 72,
  },
  sizeText: { fontSize: 12, fontWeight: '600', color: TEXT2 },
  sizeTextActive: { fontSize: 12, fontWeight: '600', color: WHITE },

  // ── Colors ──────────────────────────────────────────────────
  colorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  colorItem: { alignItems: 'center', width: 46 },
  colorDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorDotWhite: { borderColor: BORDER },
  colorDotSel: { borderColor: BLACK, borderWidth: 2.5 },
  colorCheck: { fontSize: 12, fontWeight: '800' },
  colorLabel: { fontSize: 9, color: TEXT3, marginTop: 4, textAlign: 'center' },

  // ── Category ────────────────────────────────────────────────
  catSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    borderStyle: 'dashed',
    backgroundColor: SURFACE,
  },
  catSelectText: { fontSize: 13, color: TEXT3, fontWeight: '500' },
  catList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  catPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: BLACK,
    backgroundColor: BLACK,
  },
  catPillText: { fontSize: 12, fontWeight: '500', color: WHITE },
  catPillX: { fontSize: 11, color: '#FFFFFF99', fontWeight: '700' },

  // ── Status ──────────────────────────────────────────────────
  statusRow: { flexDirection: 'row', gap: 8 },
  statusBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: SURFACE,
  },
  // Active = green ring (Active listing)
  statusBtnActive: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#22C55E',
    backgroundColor: '#F0FDF4',
  },
  // Selected = dark (Inactive listing chosen)
  statusBtnSelected: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BLACK,
    backgroundColor: BLACK,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { fontSize: 13, fontWeight: '500', color: TEXT2 },
  statusTextActive: { fontSize: 13, fontWeight: '600', color: '#16A34A' },
  statusTextSelected: { fontSize: 13, fontWeight: '500', color: WHITE },

  // ── Quick Set ────────────────────────────────────────────────
  quickSetBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: SURFACE,
  },
  quickSetText: { fontSize: 12, fontWeight: '500', color: TEXT2 },

  // ── Price / Stock display ───────────────────────────────────
  priceDisplay: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 3,
    marginBottom: 10,
  },
  priceCurrency: { fontSize: 15, fontWeight: '600', color: TEXT2 },
  priceValue: {
    fontSize: 28,
    fontWeight: '700',
    color: TEXT,
    letterSpacing: -0.5,
  },
  priceEmpty: { fontSize: 24, fontWeight: '600', color: TEXT3 },
  stockDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  stockNum: { fontSize: 28, fontWeight: '700', color: TEXT },
  stockUnit: { fontSize: 13, color: TEXT2 },
  stockBadge: {
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 20,
    backgroundColor: SURFACE,
    borderWidth: 0.5,
    borderColor: BORDER,
  },
  stockBadgeWarn: {
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 20,
    backgroundColor: '#FFFBEB',
    borderWidth: 0.5,
    borderColor: '#FDE68A',
  },
  stockBadgeText: { fontSize: 11, fontWeight: '600', color: TEXT2 },
  stockBadgeWarnText: { fontSize: 11, fontWeight: '600', color: '#92400E' },

  // ── Footer ──────────────────────────────────────────────────
  footer: { flexDirection: 'row', gap: 10, marginTop: 4 },
  discardBtn: {
    flex: 1,
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: WHITE,
  },
  discardText: { fontSize: 14, fontWeight: '500', color: TEXT2 },
  submitBtn: {
    flex: 2.5,
    height: 50,
    borderRadius: 10,
    backgroundColor: BLACK,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  submitBtnText: { fontSize: 15, fontWeight: '600', color: WHITE },
});

// ── Modal Styles ─────────────────────────────────────────────
export const modalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: WHITE,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '75%',
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: BORDER,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 2,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F3F4F6',
  },
  sheetTitle: { fontSize: 16, fontWeight: '700', color: TEXT },
  closeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: SURFACE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeBtnText: { fontSize: 11, color: TEXT2, fontWeight: '700' },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    padding: 20,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: SURFACE,
  },
  chipActive: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BLACK,
    backgroundColor: BLACK,
  },
  chipText: { fontSize: 13, fontWeight: '500', color: TEXT2 },
  chipTextActive: { fontSize: 13, fontWeight: '500', color: WHITE },
  chipX: { fontSize: 10, color: WHITE, marginLeft: 4 },
  footer: {
    flexDirection: 'row',
    gap: 10,
    padding: 20,
    borderTopWidth: 0.5,
    borderTopColor: '#F3F4F6',
  },
  cancelBtn: {
    flex: 1,
    height: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: SURFACE,
  },
  cancelText: { fontSize: 14, fontWeight: '500', color: TEXT2 },
  saveBtn: {
    flex: 2,
    height: 46,
    borderRadius: 8,
    backgroundColor: BLACK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveText: { fontSize: 14, fontWeight: '600', color: WHITE },

  // ── Stock modal ──────────────────────────────────────────────
  stockBody: { padding: 20 },
  stockLabel: { fontSize: 15, fontWeight: '700', color: TEXT, marginBottom: 4 },
  stockSub: { fontSize: 12, color: TEXT2, marginBottom: 20 },
  qtyRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  qtyBtn: {
    width: 50,
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: SURFACE,
  },
  qtyBtnText: { fontSize: 24, color: TEXT, fontWeight: '500' },
  qtyInput: {
    flex: 1,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '700',
    color: TEXT,
    borderWidth: 1,
    borderColor: BORDER,
    height: 50,
    borderRadius: 10,
    backgroundColor: SURFACE,
  },
  quickRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
  quickBtn: {
    flex: 1,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: SURFACE,
  },
  quickBtnText: { fontSize: 12, fontWeight: '500', color: TEXT2 },
});